### ISSUE TITLE
TODO for new transmissionpacket structure

### ISSUE THREAD

**Issue by Alan-JH** [TJREVERB/pfs-rewrite#22]
- [x] Use set_time() instead of using datetime to set timestamp in execute() or wherever
- [x] Instantiate FullPackets instead of TransmissionPackets in radio receive functions
- [x] Instantiate UnsolicitedData instead of TransmissionPackets in appropriate functions called by mode classes
- [x] Set numerical bool instead of return_code in command executor when transmitting an error or notification
- [x] Update iridium encoding to account for removed return_code and changed encoding order
- [x] Update iridium and aprs packet splitting to account for new descriptor sizes

**Comment by Alan-JH** [comment]
Also unrelated to the new structure but I need to add indexing to the split packets in case they transmit out of order
